version: "3"

services:
    sync:
        build: .
        ports:
            - "3009:3000"
        volumes: 
            - $PWD/data:/data
            - ./:/app/
        labels:
        - "traefik.http.routers.sync.rule=Host(`files4u.smascha.ai`)"
        - "traefik.http.routers.sync.entrypoints=websecure"
        - "traefik.http.routers.sync.tls=true"
        - "traefik.http.routers.sync.tls.certresolver=mytlschallenge"
        restart: always
        networks:
        - proxy

networks:
  proxy:
    external: true